[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Regla para proteger el panel de administración con contraseña
[[redirects]]
  from = "/admin.html"
  to = "/.netlify/functions/get-data"
  status = 200
  force = true
  headers = { Basic-Auth = "admin:ibaiondo29" }
